services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Chemege1.
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - delivery_network
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway:
    build: ./services/api-gateway
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - delivery_network

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - delivery_network
    ports:
      - "8080:8080"

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - delivery_network
    ports:
      - "8081:8081"

networks:
  delivery_network:
    driver: bridge
