services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Chemege1.}
      POSTGRES_DB: ${POSTGRES_DB:-auth_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - auth-network

  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    environment:
      CONFIG_PATH: "/app/configs/config.yaml"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - auth-network

volumes:
  postgres_data:

networks:
  auth-network:
    driver: bridge
